### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by chanhenry54** [Andy8131/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - Make sure to include and embed relevant links in Markdown like the VSCode website for the first step
- [x] All relevant code examples written with backticks (```)
  - Make sure that code and commands like your scp command are written in code blocks using backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
  - Make sure to have headers for each section
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Good job!

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by Andy8131** [comment]
In the part where I write about commands( "cd" brings me to the home directory, while "ls" gives me a list of the visible files in that directory. "ls -a" and "ls -l" shows me all the hidden files and longer details about them.), should I include the commands in a code block? Is it fine for me to also still talk about these commands in a sentence using quotes?

**Comment by chanhenry54** [comment]
Yeah, include them in a code block. If you're using them in a sentence, generally code is still preferred, but quotes work fine as well.
